apiEndpoints:
  - name: api
    host: 'localhost:8082'
    paths: '/v1/auth/signOn'

serviceEndpoints:
  - name: auth-service
    url: 'http://localhost:3112'

pipelines:
    - name: getting-started
      apiEndpoints:
        - api
      policies:
        - name: proxy
          action:
            serviceEndpoint: auth-service
            changeOrigin: true
