inboundEndpoints:
  - name: api
    host: 'localhost:8082'
    paths:
      - '/v1/auth/*'
      - /v1/auth/signOn
    methods:
      - GET
      - POST

outboundEndpoints:
  - name: auth-service
    url: 'http://localhost:3112'
    urls: # NOT IMPLEMENTED
      - 'http://localhost:3112'
      - 'http://localhost:3113'

pipelines:
    - name: getting-started
      inboundEndpoints:
        - api
      policies:
        - name: proxy
          action:
            outboundEndpoint: auth-service
            keepOrigin: false
        - name: cors
        - name: rate-limit # NOT IMPLEMENTED
          action:
            max: 1
            windowMs: 1000
