inboundEndpoints:
  - name: auth-inbound
    host: 'localhost:3000'
    paths:
      - '/v1/auth/*'
      - /v1/auth/signOn
    methods:
      - GET
      - POST

outboundEndpoints:
  - name: auth-service
    url: 'http://localhost:3112'
    urls: # NOT IMPLEMENTED
      - 'http://localhost:3112'
      - 'http://localhost:3113'

pipelines:
    - name: first-pipeline
      inboundEndpoints:
        - auth-inbound
      plugins:
        - name: jwt
          secret: c2VjcmV0
        - name: proxy
          action:
            outboundEndpoint: auth-service
            keepOrigin: false
        - name: cors
        - name: request-transform
          action:
            body:
              duplicate:
                deviceId: anotherId
            query:
              append:
                queryKey: queryValue
        - name: response-transform
          action:
            modifyStatus: 200
            setHeaders:
              membrane-forwarded: true
            reformatBody:
              accessToken: sessionId
        - name: rate-limit # NOT IMPLEMENTED
          action:
            max: 1
            windowMs: 1000
